# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "master", "nightly", "unstable" ]
  pull_request:
    branches: [ "dev", "nightly", "d*.*.*" ]

permissions:
  contents: read

jobs:
  env:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Create VENV
      run: |
        python -m venv .venv
    - name: Activate VENV (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        source .venv/bin/activate
    - name: Activate VENV (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        .\.venv\Scripts\activate
    - name: Cache
      id: cache
      uses: actions/cache@v4.1.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ./.venv/
        # An explicit key for restoring and saving the cache
        key: ${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }}
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
        enableCrossOsArchive: false
    - name: Install dependencies
      if: ${{ steps.cache.outputs.cache-hit == 'false' }}
      run: |
        python -m pip install --upgrade pip
        pip install --prefer-binary -r requirements.txt
  test:
    needs: env
    strategy:
      matrix:
        os: [ubuntu-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}
    env:
      DISPLAY: ':99.0'
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Load Cache
      uses: actions/cache@v4.1.2
      with:
        # A list of files, directories, and wildcard patterns to cache and restore
        path: ./.venv/
        # An explicit key for restoring and saving the cache
        key: ${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        # An ordered multiline string listing the prefix-matched keys, that are used for restoring stale cache if no cache hit occurred for key. Note `cache-hit` returns false in this case.
        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }}
        # An optional boolean when enabled, allows windows runners to save or restore caches that can be restored or saved respectively on other platforms
        enableCrossOsArchive: false
        # Fail the workflow if cache entry is not found
        fail-on-cache-miss: true
    - name: Activate VENV (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        source .venv/bin/activate
        pip --version
        pip list
    - name: Activate VENV (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        .\.venv\Scripts\activate
        pip --version
        pip list
    - name: Install Requirements from Cache
      run: |
        pip --version
        pip install -r requirements.txt
        pip list
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics --exclude=.venv,build,dist
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics --exclude=.venv,build,dist
    - uses: tlambert03/setup-qt-libs@v1
    - name: build "display"
      run: |
        /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -screen 0 1920x1200x24 -ac +extension GLX
    - name: Test with pytest (isolated) & xvfb
      run: |
        pytest --disable-warnings -v
        EXIT_CODE=$?
        if [ $EXIT_CODE -eq 139 ] ; then
          echo "Segmentation fault occured. Exit with code 0."
          exit 0
        else
          exit $EXIT_CODE
        fi
  build:
    name: build
    needs: test
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        python-version: [3.12]
    runs-on: ${{ matrix.os }}
    if: ${{ github.event_name == 'push' }}
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5.3.0
      with:
        python-version: ${{ matrix.python-version }}
    - name: Load Cache
      uses: actions/cache@v4.1.2
      with:
        path: ./.venv/
        key: ${{ matrix.os }}-python-${{ matrix.python-version }}-${{ hashFiles('**/requirements.txt') }}
        restore-keys: ${{ matrix.os }}-python-${{ matrix.python-version }}
        enableCrossOsArchive: false
        fail-on-cache-miss: true
    - name: Activate VENV (Linux)
      if: ${{ matrix.os == 'ubuntu-latest' }}
      run: |
        source .venv/bin/activate
    - name: Activate VENV (Windows)
      if: ${{ matrix.os == 'windows-latest' }}
      run: |
        .\.venv\Scripts\activate
    - name: Install Requirements from Cache
      run: |
        pip install -r requirements.txt
    - name: PyInstaller Action
      uses: Martin005/pyinstaller-action@v1.2.0
      with:
        python_ver: ${{ matrix.python-version }}
        spec: 'main.py'
        requirements: 'requirements.txt'
        upload_exe_with_name: 'UEX-Trader'
        options: --onedir, --name "UEX-Trader", --windowed, --icon ./resources/uextrader_icon_resized_idL_icon.ico, --add-data ./resources/UEXTrader_icon_resized.png:resources/UEXTrader_icon_resized.png
    - name: Upload Compiled Executables
      uses: actions/upload-artifact@v4.4.3
      with:
        name: builds-${{ github.base_ref }}-${{ matrix.os }}-${{ matrix.python-version }}
        path: dist/
        if-no-files-found: error